### PR TITLE
Added config for ore generation

### PR DESCRIPTION
**Pull request by ConnorRowe**
I just created a config file and made entries so users can choose which blocks they want to generate.

### CODE REVIEW

**Comment by Zkaface** [comment]
:+1:  gonna check that for next version! Thanks a lot Connor!

**Comment by Zkaface** [comment]
atm this could fuck up the game, depending on missing tools for high tier levels! I gonna thik about it

**Comment by Zkaface** [comment]
I will implement a config, which will be in a way, that there is not "too much" of everything. The necessary blocks and items have to be in the addon - in any other case you do not need this addon =)

**Comment by ConnorRowe** [comment]
I wanted the config so I could disable the blocks I didn't want such as iron ore slagged/gold ore slagged.

**Pull request merged**
